# Generated by Django 4.0.5 on 2022-07-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_rename_group_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group',
            new_name='chat',
        ),
    ]
