# Generated by Django 4.0.5 on 2022-07-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_rename_group_message_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
    ]
