# Generated by Django 4.0.5 on 2022-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='baseapp.person'),
        ),
    ]
