# Generated by Django 4.0.5 on 2022-07-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_alter_person_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contacts',
        ),
    ]
