# Generated by Django 4.0.5 on 2022-07-12 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0007_remove_person_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
