
export const CHATS_LIST_REQUEST = 'CHATS_LIST_REQUEST'
export const CHATS_LIST_SUCCESS = 'CHATS_LIST_SUCCESS'
export const CHATS_LIST_FAIL = 'CHATS_LIST_FAIL'
export const CHATS_LIST_RESET = 'CHATS_LIST_RESET'
