
export const CHATS_LIST_REQUEST = 'CHATS_LIST_REQUEST'
export const CHATS_LIST_SUCCESS = 'CHATS_LIST_SUCCESS'
export const CHATS_LIST_FAIL = 'CHATS_LIST_FAIL'
export const CHATS_LIST_RESET = 'CHATS_LIST_RESET'
export const UPDATE_CHAT_MESSAGES = 'UPDATE_CHAT_MESSAGES'
export const UPDATE_CHATS_LIST = 'UPDATE_CHATS_LIST'


export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT'
export const RESET_CURRENT_CHAT = 'RESET_CURRENT_CHAT'


export const START_CHAT_REQUEST = 'START_CHAT_REQUEST'
export const START_CHAT_SUCCESS = 'START_CHAT_SUCCESS'
export const START_CHAT_FAIL = 'START_CHAT_FAIL'
