
export const CHATS_LIST_REQUEST = 'CHATS_LIST_REQUEST'
export const CHATS_LIST_SUCCESS = 'CHATS_LIST_SUCCESS'
export const CHATS_LIST_FAIL = 'CHATS_LIST_FAIL'
export const CHATS_LIST_RESET = 'CHATS_LIST_RESET'


export const SET_CURRENT_CHAT_ID = 'SET_CURRENT_CHAT_ID'
export const RESET_CURRENT_CHAT_ID = 'RESET_CURRENT_CHAT_ID'


export const START_CHAT_REQUEST = 'START_CHAT_REQUEST'
export const START_CHAT_SUCCESS = 'START_CHAT_SUCCESS'
export const START_CHAT_FAIL = 'START_CHAT_FAIL'
