
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'


export const USERNAME_CHECK_REQUEST = 'USERNAME_CHECK_REQUEST'
export const USERNAME_CHECK_SUCCESS = 'USERNAME_CHECK_SUCCESS'
export const USERNAME_CHECK_FAIL = 'USERNAME_CHECK_FAIL'
