export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET'

export const USER_LOGOUT = 'USER_LOGOUT'


export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const SIGNUP_RESET = 'SIGNUP_RESET'


export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL'
export const UPDATE_USER_PROFILE_RESET = 'UPDATE_USER_PROFILE_RESET'
